[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = [
    "@solady-utils/=lib/solady/src/utils/",
    "forge-std/=lib/forge-std/src/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
]
